#!/bin/bash
SSH_KEY_NAME=[% deploy.ssh_key_name %]
SSH_OPTS="-o StrictHostKeyChecking=no"
INIT_MODULE="[% module_name %]"

APP_TYPE=service
APP_NAME=redis

DOMAIN=[% deploy.domain %]

NODE_NAME=[% node.name %]
NODE_VPN_IP=[% vpn_ctrl.vpn_ip %]
REDIS_USER=[% app.redis_user %]
DYNO_PORT=[% app.dyno_port %]

ETCD_NODES="[% FOR host IN etcd.nodes %][% host.name %][%- " " IF not loop.last %][% END %]"

ETCD_NODE_HOSTS_FILE=$(cat <<- EOF
[% FOR host IN etcd.nodes %]

[% host.vpn_ip %][% " " %][% host.name %]
[% END %]
EOF
)
