---

# This Playbook runs all the common plays in the deployment

#- name: Refresh repository cache
#  shell: yum clean all && yum makecache

- name: Install unzip and java
  yum:
    name: ['unzip', 'java-1.8.0-openjdk-devel']
    state: present

#- name: Enable port On SELinux
#  seport:
#    ports: "2700-2703,{{mongos_port}},{{mongoc_port}}"
#    proto: tcp
#    setype: mongod_port_t
#    state: present
#  when: ansible_selinux is defined and ansible_selinux != False and ansible_selinux.status == 'enabled'
    
#- name: Create the mongod user
#  user: name=elasticsearch comment="MongoD"

#- name: Create the data directory for the namenode metadata
#  file: path={{ mongodb_datadir_prefix }} owner=mongod group=mongod state=directory setype=mongod_var_lib_t recurse=true
