#!/bin/bash
SSH_KEY_NAME=[% deploy.ssh_key_name %]
SSH_OPTS="-o StrictHostKeyChecking=no"
INIT_MODULE="[% module_name %]"

APP_TYPE=[% app.type %]
APP_NAME=[% app.name %]
EXPOSE=[% app.expose %]
ENV_PREFIX=[% app.env_prefix %]
MINIO_USER=[% app.user %]

DOMAIN=[% deploy.domain %]

NODE_NAME=[% node.name %]
NODE_VPN_IP=[% vpn_ctrl.vpn_ip %]


ETCD_NODES="[% FOR host IN etcd.nodes %][% host.name %][%- " " IF not loop.last %][% END %]"

ETCD_NODE_HOSTS_FILE=$(cat <<- EOF
[% FOR host IN etcd.nodes %]

[% host.vpn_ip %][% " " %][% host.name %]
[% END %]
EOF
)
